branches:
  - "10.0"
  - "11.0"
  - "12.0"
  - "13.0"

repos:
  itpp-labs/misc-addons:
  itpp-labs/pos-addons:
  itpp-labs/website-addons:
  itpp-labs/mail-addons:
  itpp-labs/access-addons:
  itpp-labs/sync-addons:
