version: "2.4"

services:
  odoo:
    ports:
      - "127.0.0.1:6899:6899"
      - "127.0.0.1:8069:8069"
    depends_on:
      - smtp
      - wdb
    command: >
      odoo
      --limit-memory-soft=0
      --limit-time-real-cron=9999999
      --limit-time-real=9999999
      --workers=0
      --init=$MODULES
      --load=$LOAD_MODULES
      $ODOO_EXTRA_ARG

  smtp:
    image: mailhog/mailhog
    ports:
      - "127.0.0.1:8025:8025"

  wdb:
    image: kozea/wdb
    ports:
      - "127.0.0.1:1984:1984"
    # HACK https://github.com/Kozea/wdb/issues/136
    stop_signal: KILL
